/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author ingerioj
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Dep = new javax.swing.JButton();
        Jdep = new javax.swing.JButton();
        Jtod = new javax.swing.JButton();
        Jfam = new javax.swing.JButton();
        Jclien = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Panel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tclientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tdeportivo = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tclasico = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tfamiliar = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Terreneitor = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        Salida = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        agcli = new javax.swing.JMenu();
        Agregar = new javax.swing.JMenuItem();
        Gdeport = new javax.swing.JMenuItem();
        Gclas = new javax.swing.JMenuItem();
        Gtodo = new javax.swing.JMenuItem();
        Gfami = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Alqui = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Dep.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 18)); // NOI18N
        Dep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/baby-car_3089803.png"))); // NOI18N
        Dep.setText("Tabla De A.Clasicos");

        Jdep.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 18)); // NOI18N
        Jdep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/sport-car_3085330 (2).png"))); // NOI18N
        Jdep.setText("Tabla De A.Deportivos");
        Jdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JdepActionPerformed(evt);
            }
        });

        Jtod.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 18)); // NOI18N
        Jtod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/electric-car_5347678 (1).png"))); // NOI18N
        Jtod.setText("Tabla De A.TodoTerreno");

        Jfam.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 18)); // NOI18N
        Jfam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/car_6750484 (1).png"))); // NOI18N
        Jfam.setText("Tabla De A.Familiar");

        Jclien.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 18)); // NOI18N
        Jclien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/profile_3135768.png"))); // NOI18N
        Jclien.setText("Tabla De Clientes");
        Jclien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JclienActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell Extra Bold", 3, 24)); // NOI18N
        jLabel1.setText("Top Gear");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Jfam, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtod)
                    .addComponent(Dep, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jdep, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(Jclien, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(128, 128, 128)
                .addComponent(Jclien)
                .addGap(33, 33, 33)
                .addComponent(Jdep)
                .addGap(34, 34, 34)
                .addComponent(Dep)
                .addGap(31, 31, 31)
                .addComponent(Jtod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(Jfam)
                .addGap(85, 85, 85))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 440, 750));

        Panel.setBackground(new java.awt.Color(215, 225, 245));

        Tclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Identificacion", "M.Auto Alquilado", "Modelo"
            }
        ));
        jScrollPane1.setViewportView(Tclientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        Panel.addTab("tab1", jPanel1);

        Tdeportivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Velocidad Maxima", "Tiempo De Acceleracion"
            }
        ));
        jScrollPane2.setViewportView(Tdeportivo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        Panel.addTab("tab2", jPanel3);

        Tclasico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Fecha De Fabricacion", "Valor Historico", "Estado"
            }
        ));
        jScrollPane3.setViewportView(Tclasico);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        Panel.addTab("tab3", jPanel4);

        Tfamiliar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Capacidad De Personas"
            }
        ));
        jScrollPane4.setViewportView(Tfamiliar);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        Panel.addTab("tab4", jPanel5);

        Terreneitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Ancho Del Chacis", "Tamaño De La Suspension"
            }
        ));
        jScrollPane5.setViewportView(Terreneitor);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        Panel.addTab("tab5", jPanel6);

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, -31, -1, 780));

        Salida.setText("Archivo");

        Salir.setText("Salir");
        Salida.add(Salir);

        jMenuBar1.add(Salida);

        agcli.setText("Registro");

        Agregar.setText("Agregar Cliente");
        agcli.add(Agregar);

        Gdeport.setText("Agregar A.Deportivo");
        agcli.add(Gdeport);

        Gclas.setText("Agregar A.Clasico");
        agcli.add(Gclas);

        Gtodo.setText("Agregar A.TodoTerreno");
        agcli.add(Gtodo);

        Gfami.setText("Agregar A.Familiar");
        agcli.add(Gfami);

        jMenuBar1.add(agcli);

        jMenu3.setText("Funciones");

        Alqui.setText("Alquiler");
        jMenu3.add(Alqui);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JdepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JdepActionPerformed

    private void JclienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JclienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JclienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar;
    private javax.swing.JMenuItem Alqui;
    private javax.swing.JButton Dep;
    private javax.swing.JMenuItem Gclas;
    private javax.swing.JMenuItem Gdeport;
    private javax.swing.JMenuItem Gfami;
    private javax.swing.JMenuItem Gtodo;
    private javax.swing.JButton Jclien;
    private javax.swing.JButton Jdep;
    private javax.swing.JButton Jfam;
    private javax.swing.JButton Jtod;
    public javax.swing.JTabbedPane Panel;
    private javax.swing.JMenu Salida;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JTable Tclasico;
    public javax.swing.JTable Tclientes;
    public javax.swing.JTable Tdeportivo;
    public javax.swing.JTable Terreneitor;
    public javax.swing.JTable Tfamiliar;
    private javax.swing.JMenu agcli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JTable getTclasico() {
        return Tclasico;
    }

    public void setTclasico(JTable Tclasico) {
        this.Tclasico = Tclasico;
    }

    public JTable getTclientes() {
        return Tclientes;
    }

    public void setTclientes(JTable Tclientes) {
        this.Tclientes = Tclientes;
    }

    public JTable getTdeportivo() {
        return Tdeportivo;
    }

    public void setTdeportivo(JTable Tdeportivo) {
        this.Tdeportivo = Tdeportivo;
    }

    public JTable getTerreneitor() {
        return Terreneitor;
    }

    public void setTerreneitor(JTable Terreneitor) {
        this.Terreneitor = Terreneitor;
    }

    public JTable getTfamiliar() {
        return Tfamiliar;
    }

    public void setTfamiliar(JTable Tfamiliar) {
        this.Tfamiliar = Tfamiliar;
    }

    public JButton getDep() {
        return Dep;
    }

    public void setDep(JButton Dep) {
        this.Dep = Dep;
    }

    public JButton getJclien() {
        return Jclien;
    }

    public void setJclien(JButton Jclien) {
        this.Jclien = Jclien;
    }

    public JButton getJdep() {
        return Jdep;
    }

    public void setJdep(JButton Jdep) {
        this.Jdep = Jdep;
    }

    public JButton getJfam() {
        return Jfam;
    }

    public void setJfam(JButton Jfam) {
        this.Jfam = Jfam;
    }

    public JButton getJtod() {
        return Jtod;
    }

    public void setJtod(JButton Jtod) {
        this.Jtod = Jtod;
    }

    public JMenu getSalida() {
        return Salida;
    }

    public void setSalida(JMenu Salida) {
        this.Salida = Salida;
    }

    public JMenuItem getAgregar() {
        return Agregar;
    }

    public void setAgregar(JMenuItem Agregar) {
        this.Agregar = Agregar;
    }

    public JMenuItem getGclas() {
        return Gclas;
    }

    public void setGclas(JMenuItem Gclas) {
        this.Gclas = Gclas;
    }

    public JMenuItem getGdeport() {
        return Gdeport;
    }

    public void setGdeport(JMenuItem Gdeport) {
        this.Gdeport = Gdeport;
    }

    public JMenuItem getGfami() {
        return Gfami;
    }

    public void setGfami(JMenuItem Gfami) {
        this.Gfami = Gfami;
    }

    public JMenuItem getGtodo() {
        return Gtodo;
    }

    public void setGtodo(JMenuItem Gtodo) {
        this.Gtodo = Gtodo;
    }

    public JMenuItem getAlqui() {
        return Alqui;
    }

    public void setAlqui(JMenuItem Alqui) {
        this.Alqui = Alqui;
    }

    public JMenuItem getSalir() {
        return Salir;
    }

    public void setSalir(JMenuItem Salir) {
        this.Salir = Salir;
    }

    

}
